### ISSUE TITLE
Loading all orders causing Magento to crash in a large environment

### ISSUE THREAD

**Issue by phillipesouza** [paymeebrasil/magento-1.x#5]
Boa noite,

Num ambiente com um número considerável de pedidos, ao finalizar a compra através do Paymee retorna erro por alto consumo do banco. Isso acontece porque no OrderController a redirectAction() faz uma requisição chamando toda Collection de pedidos feitos na loja causando o erro. Uma solução é chamar apenas a order do pedido em si.

**Comment by jalmoreno** [comment]
fixed
